root = "."
tmp_dir = "tmp"

[build]
cmd = "sh scripts/build-dev.sh"
full_bin = "OC_DEV=true OC_DEBUG=true OC_HTTP=0.0.0.0:9081 OC_ENABLE_SIGNUP=true ./tmp/main serve"
delay = 1000
exclude_dir = ["assets", "ui", "oc_data", "scripts"]
include_ext = ["go"]
exclude_regex = ["_test\\.go"]
